server:
  port: 8100

logging.level:
  org.hibernate:
    SQL: TRACE
    type: TRACE

---

spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  config:
    activate:
      on-profile:

---

spring:
  # local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: root
    password: 1234

  jpa:
    properties.hibernate:
      format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: local
