server:
  port: 8100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: root
    password: 1234

  jpa:
    properties.hibernate:
      format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never

logging.level:
  org.hibernate:
    SQL: TRACE
    type: TRACE
